### ISSUE TITLE
error C2061: syntax error: identifier 'ole2_read'

### ISSUE THREAD

**Issue by leocavalcante** [libxls/libxls#52]
I'm newbie to C, but is it `ssize_t` indeed?
https://github.com/libxls/libxls/blob/master/include/libxls/ole.h#L181
Should be `size_t`?

**Comment by evanmiller** [comment]
`ssize_t` is signed `size_t`, should be okay.

Please post full compiler version and output if there is an error.

**Comment by leocavalcante** [comment]
```pwsh
~ cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

**Comment by QuLogic** [comment]
Compiling C or C++? Is this fixed/broken by #49?

**Comment by evanmiller** [comment]
I think the problem was removing <sys/types.h>. I have restored it in dev.

**Comment by leocavalcante** [comment]
Not yet :/
```pwsh
libxls [master]~ git rev-parse HEAD
e5fe0ab9555a02b04e067487898da623e2bcff6e

libxls [master]~ .\build.ps1
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

xls.c
c:\users\leo\projects\libxls\include\libxls\../libxls/ole.h(181): error C2061: syntax error: identifier 'ole2_read'
c:\users\leo\projects\libxls\include\libxls\../libxls/ole.h(181): error C2059: syntax error: ';'
c:\users\leo\projects\libxls\include\libxls\../libxls/ole.h(181): error C2059: syntax error: '<parameter-list>'
.\src\xls.c(1628): warning C4047: 'return': 'const char *' differs in levels of indirection from 'int'
xlstool.c
c:\users\leo\projects\libxls\include\libxls\../libxls/ole.h(181): error C2061: syntax error: identifier 'ole2_read'
c:\users\leo\projects\libxls\include\libxls\../libxls/ole.h(181): error C2059: syntax error: ';'
c:\users\leo\projects\libxls\include\libxls\../libxls/ole.h(181): error C2059: syntax error: '<parameter-list>'
ole.c
c:\users\leo\projects\libxls\src\../include/libxls/ole.h(181): error C2061: syntax error: identifier 'ole2_read'
c:\users\leo\projects\libxls\src\../include/libxls/ole.h(181): error C2059: syntax error: ';'
c:\users\leo\projects\libxls\src\../include/libxls/ole.h(181): error C2059: syntax error: '<parameter-list>'
.\src\ole.c(58): error C2061: syntax error: identifier 'sector_read'
.\src\ole.c(58): error C2059: syntax error: ';'
.\src\ole.c(58): error C2059: syntax error: '<parameter-list>'
.\src\ole.c(59): error C2061: syntax error: identifier 'read_MSAT'
.\src\ole.c(59): error C2059: syntax error: ';'
.\src\ole.c(59): error C2059: syntax error: '<parameter-list>'
.\src\ole.c(161): error C2061: syntax error: identifier 'ole2_read'
.\src\ole.c(161): error C2059: syntax error: ';'
.\src\ole.c(161): error C2059: syntax error: '<parameter-list>'
.\src\ole.c(388): error C2061: syntax error: identifier 'ole2_read_header'
.\src\ole.c(388): error C2059: syntax error: ';'
.\src\ole.c(388): error C2059: syntax error: '<parameter-list>'
.\src\ole.c(457): error C2061: syntax error: identifier 'ole2_read_body'
.\src\ole.c(457): error C2059: syntax error: ';'
.\src\ole.c(457): error C2059: syntax error: '<parameter-list>'
.\src\ole.c(636): error C2061: syntax error: identifier 'sector_read'
.\src\ole.c(636): error C2059: syntax error: ';'
.\src\ole.c(636): error C2059: syntax error: '<parameter-list>'
.\src\ole.c(657): error C2061: syntax error: identifier 'read_MSAT_header'
.\src\ole.c(657): error C2059: syntax error: ';'
.\src\ole.c(657): error C2059: syntax error: '<parameter-list>'
.\src\ole.c(677): error C2061: syntax error: identifier 'read_MSAT_body'
.\src\ole.c(677): error C2059: syntax error: ';'
.\src\ole.c(677): error C2059: syntax error: '<parameter-list>'
.\src\ole.c(738): error C2061: syntax error: identifier 'read_MSAT_trailer'
.\src\ole.c(738): error C2059: syntax error: ';'
.\src\ole.c(738): error C2059: syntax error: '<parameter-list>'
.\src\ole.c(783): error C2061: syntax error: identifier 'read_MSAT'
.\src\ole.c(783): error C2059: syntax error: ';'
.\src\ole.c(783): error C2059: syntax error: '<parameter-list>'
endian.c
c:\users\leo\projects\libxls\include\libxls\../libxls/ole.h(181): error C2061: syntax error: identifier 'ole2_read'
c:\users\leo\projects\libxls\include\libxls\../libxls/ole.h(181): error C2059: syntax error: ';'
c:\users\leo\projects\libxls\include\libxls\../libxls/ole.h(181): error C2059: syntax error: '<parameter-list>'
Generating Code...
```

If I find for all occurrences of `ssize_t` and replace by `size_t` then build:
```pwsh
libxls [master]~ .\build.ps1
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

xls.c
xlstool.c
ole.c
endian.c
Generating Code...
Microsoft (R) Incremental Linker Version 14.16.27027.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:xls.dll
/dll
/implib:xls.lib
xls.obj
xlstool.obj
ole.obj
endian.obj

libxls [master]~ ls | grep .dll
-a----         3/8/2019  11:33 AM         253952 xls.dll
```
Voilà!

##### build.ps1
```pwsh
Remove-Item .\*.obj

cl `
  -I .\ `
  -I .\include `
  -LD `
  .\src\xls.c `
  .\src\xlstool.c `
  .\src\ole.c `
  .\src\endian.c
```

`bootstrap` and `configure` to have a `config.h` by MSYS2.
And indeed it works fine on MSYS2 gcc.

**Comment by leocavalcante** [comment]
"ssize_t msvc" on Google is very elucidating. It seems that it is POSIX compliant only, not standard C.

Found some cool answers that it could be defined:
```c
#if defined(_MSC_VER)
#include <BaseTsd.h>
typedef SSIZE_T ssize_t;
#endif
```

```c
#include <limits.h>
#include <stddef.h>

#if SIZE_MAX == UINT_MAX
typedef int ssize_t;        /* common 32 bit case */
#elif SIZE_MAX == ULONG_MAX
typedef long ssize_t;       /* linux 64 bits */
#elif SIZE_MAX == ULLONG_MAX
typedef long long ssize_t;  /* windows 64 bits */
#elif SIZE_MAX == USHRT_MAX
typedef short ssize_t;      /* is this even possible? */
#else
#error platform has exotic SIZE_MAX
#endif
```

**Comment by silvioprog** [comment]
hi dudes. since the build passes fine in the appveyor cc, it would be nice to send the libxls to the msys repositories. :-)
